/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package joe;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.Date;
import org.json.simple.JSONObject;    

import org.bson.Document;
import org.bson.types.ObjectId;

import org.bson.conversions.Bson;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.model.Projections;
import com.mongodb.client.MongoCursor;

public class App extends JFrame {
        private static JLabel outputlabel=new JLabel( );
        private static JButton nameButton= new JButton("Send");
        private static JLabel questionLabel=new JLabel("Enter your question here");
        private static JTextField messageField=new JTextField(25);
        private static String uri = "mongodb+srv://josbudney:ZbXSdrVMvBHnWRb7@bay-path.tkovhhw.mongodb.net/?retryWrites=true&w=majority";

        String outputMessage="Thank you for the information";
       
       

        public static void buttonClicked(ActionEvent e){

            try (MongoClient mongoClient = MongoClients.create(uri)) {
                MongoDatabase database = mongoClient.getDatabase("Q-Up");
                MongoCollection<Document> collection = database.getCollection("messages");
                Message message = new Message(messageField.getText());
                collection.insertOne( message.getDocument() );
            }
    
        }         
         
    public static void main(String[] args) {
        
        App window = new App();
        window.setSize(1000,500);
        window.setVisible(true);
        window.setTitle("My JFrame");
        window.setLayout(new FlowLayout());

        window.getContentPane().add(questionLabel);
        window.getContentPane().add(messageField);
        window.getContentPane().add(new JLabel("    "));
        window.getContentPane().add(nameButton);
       
        window.getContentPane().add(outputlabel);
        nameButton.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
                buttonClicked(e);
            }
        });
        try (MongoClient mongoClient = MongoClients.create(uri)) {
            MongoDatabase database = mongoClient.getDatabase("Q-Up");
            MongoCollection<Document> collection = database.getCollection("messages");
            System.out.println(collection.distinct("message", String.class).toString());
            //Bson projectionFields = Projections.fields(
            //    Projections.include("_id"));
            //MongoCursor<Document> cursor = collection.find()
            //    .projection(projectionFields).iterator();
            //try {
            //    while(cursor.hasNext()) {
            //        System.out.println(cursor.next().toJson());
            //    }
            //} finally {
            //    cursor.close();
            //  }
        }
    
        window.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
}
